@startuml ゲーム進行
participant クライアント as cl
participant サーバ as sv
participant ゲーム管理 as gm
participant 盤面管理 as bord

group ゲーム初期化
    cl -> sv : ゲーム開始 \n 先攻後攻情報 \n パス回数
    sv -> gm : セッション情報
    gm -> bord
    bord -> bord : 盤面初期化
    bord -> gm
    gm -> sv
    sv -> cl : respons
end

group ゲーム中
    alt 置き石可能
        cl -> sv : 石座標
        sv -> gm
        gm <-> bord : プレーヤ石情報設定
        gm -> 対戦CPU
        対戦CPU -> 対戦CPU : CPU石設定
        対戦CPU -> gm
        gm <-> bord : 盤面情報取得
        gm -> sv
        sv -> cl
        cl <-> cl : 盤面描画
    else パス
        cl -> sv : パス通知
        sv -> gm
        gm <-> gm : パス回数更新
        gm -> sv
        sv -> cl : 現在のパス回数
        cl <-> cl : パス回数更新
    end
end
@enduml

@startuml 画面遷移
[*] --> 初期画面    
初期画面 --> 盤面画面 : ゲーム開始ボタン押下
盤面画面 --> 盤面画面
盤面画面 --> 勝敗画面 : 勝敗情報
勝敗画面 --> 初期画面 : もう一度プレイ
初期画面 --> [*]

初期画面 : 先攻後攻選択

盤面画面 : 石の数
盤面画面 : 降参ボタン
盤面画面 : (パスボタン)

勝敗画面 : 石の数
勝敗画面 : 勝敗メッセージ
@enduml